# conda env create -f environment.yml
name: masterclass
channels:
  - defaults
  - conda-forge
dependencies:
- pip
- python
- ipython
- jupyter
- matplotlib
- numpy
- pandas
- seaborn
- plotly
- scikit-learn
